clr1=input("Enter the colours:")
clr_list1=clr1.split(",")
print(clr_list1)
clr2=input("Enter the colours:")
clr_list2=clr2.split(",")
print(clr_list2)
x=(set(clr_list1).difference(clr_list2))
print(x)